#!/usr/bin/env bash
# spec-loop init — per-project setup wizard

cmd_init() {
  print_header
  echo ""

  # Check for existing config
  if [[ -f "$SPECLOOPRC" && "$INIT_FORCE" != "true" ]]; then
    die ".speclooprc already exists. Use --force to overwrite."
  fi

  # Detect project type
  local detected_type
  detected_type=$(detect_project_type)

  # Detect commands
  local detected_verify detected_test
  detected_verify=$(detect_verify_command "$detected_type")
  detected_test=$(detect_test_command "$detected_type")

  # Allow CLI overrides
  [[ -n "$INIT_VERIFY_CMD" ]] && detected_verify="$INIT_VERIFY_CMD"
  [[ -n "$INIT_TEST_CMD" ]] && detected_test="$INIT_TEST_CMD"

  if [[ "$INIT_NO_WIZARD" == "true" ]]; then
    _init_write "$detected_type" "$detected_verify" "$detected_test"
  else
    _init_wizard "$detected_type" "$detected_verify" "$detected_test"
  fi
}

_init_wizard() {
  local project_type="$1"
  local verify_cmd="$2"
  local test_cmd="$3"

  phase "Initializing spec-loop"
  echo ""

  # Project type
  step_info "Detected project type: ${C_BOLD}${project_type}${C_RESET}"
  echo ""
  read -r -p "  Project type [$project_type]: " user_type
  project_type="${user_type:-$project_type}"

  # Verify command
  if [[ -n "$verify_cmd" ]]; then
    step_info "Detected verify command: ${C_DIM}${verify_cmd}${C_RESET}"
  else
    step_warn "Could not detect verify command"
  fi
  echo ""
  read -r -p "  Verify command [$verify_cmd]: " user_verify
  verify_cmd="${user_verify:-$verify_cmd}"

  # Test command
  if [[ -n "$test_cmd" ]]; then
    step_info "Detected test command: ${C_DIM}${test_cmd}${C_RESET}"
  else
    step_warn "Could not detect test command"
  fi
  echo ""
  read -r -p "  Test command [$test_cmd]: " user_test
  test_cmd="${user_test:-$test_cmd}"

  echo ""
  _init_write "$project_type" "$verify_cmd" "$test_cmd"
}

_init_write() {
  local project_type="$1"
  local verify_cmd="$2"
  local test_cmd="$3"

  # Write .speclooprc
  cat > "$SPECLOOPRC" <<EOF
# spec-loop configuration
# Generated by spec-loop init on $(date '+%Y-%m-%d')

# Project
PROJECT_TYPE="$project_type"
VERIFY_COMMAND="$verify_cmd"
TEST_COMMAND="$test_cmd"

# Claude Code
# CLAUDE_MODEL=""

# Loop limits
# MAX_LOOPS=25
# MAX_REVIEW_FIX_LOOPS=3

# Safety
# CB_NO_PROGRESS_THRESHOLD=3
# CB_COOLDOWN_MINUTES=30

# UI
# SHOW_PREVIEW=true
# PREVIEW_LINES=5

# Paths
# SPECS_DIR=".agents/specs"
# SESSION_DIR=".spec-loop/sessions"
EOF

  step_ok "Created .speclooprc"

  # Create directories
  mkdir -p ".agents/specs"
  mkdir -p ".spec-loop/sessions"
  step_ok "Created .agents/ and .spec-loop/ directories"

  # Copy templates if they don't exist
  local templates_src="${LIB_DIR}/../.agents/templates"
  if [[ -d "$templates_src" ]]; then
    mkdir -p ".agents/templates"
    for tmpl in spec.md task.md progress.md; do
      if [[ ! -f ".agents/templates/$tmpl" && -f "$templates_src/$tmpl" ]]; then
        cp "$templates_src/$tmpl" ".agents/templates/$tmpl"
      fi
    done
    step_ok "Copied templates to .agents/templates/"
  fi

  # Create decisions.md if it doesn't exist
  if [[ ! -f ".agents/decisions.md" ]]; then
    cat > ".agents/decisions.md" <<'DECISIONS'
# Decisions

Design decisions made during development. Append new entries at the bottom.
DECISIONS
    step_ok "Created .agents/decisions.md"
  fi

  # Create starter AGENTS.md if none exists
  if [[ ! -f "AGENTS.md" ]]; then
    cat > "AGENTS.md" <<'AGENTS'
# AGENTS.md

Project conventions and architecture rules for AI agents.

## Project Overview

<!-- Describe what this project does, its architecture, and key technologies. -->

## Conventions

<!-- Add your project's coding conventions:
- Naming: files, functions, variables
- Structure: where things live, how modules are organized
- Patterns: common patterns to follow
- Anti-patterns: things to avoid
-->

## Review Checklist

<!-- Add project-specific review criteria:
- Architecture rules
- Type safety requirements
- Test coverage expectations
- Security considerations
-->
AGENTS
    step_ok "Created starter AGENTS.md"
  fi

  # Update .gitignore
  _update_gitignore

  echo ""
  step_ok "${C_BOLD}spec-loop initialized${C_RESET}"
  echo ""
  step_info "Next: edit AGENTS.md with your project's rules"
  step_info "Then:  run ${C_BOLD}/spec${C_RESET} to create your first feature spec"
}

_update_gitignore() {
  local gitignore=".gitignore"
  local marker="# spec-loop"
  local entries=(
    ".spec-loop/"
  )

  # Don't duplicate if marker already present
  if [[ -f "$gitignore" ]] && grep -qF "$marker" "$gitignore"; then
    return
  fi

  {
    echo ""
    echo "$marker"
    for entry in "${entries[@]}"; do
      echo "$entry"
    done
  } >> "$gitignore"

  step_ok "Updated .gitignore"
}
